### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by mishra283** [Waffleboy/IVLE-EEEE#1]
```
  File "main.py", line 18, in <module>
    API_KEY = os.environ["oSEodEeuCLPyFY2IXXXX"]
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'oSEodEeuCLPyFY2IXXXX'

```
@Waffleboy For some reason, I get this error on `python main.py`

**Comment by Waffleboy** [comment]
Er.. `os.environ` access your environment variables in a dictionary form to find the key. in your case, you probably want

  API_KEY = "oSEodEeuCLPyFY2IWO5zm"

Although now your key is in the open and i *strongly* recommend changing it
